---
- name: Récupérer la version IOS
  hosts: routers
  gather_facts: no

  tasks:
    - name: Exécuter show version
      ios_command:
        commands:
          - show version
      register: output

    - name: Afficher le résultat
      debug:
        var: output.stdout_lines
